#   ?????debug?????feign????????
logging:
  level:
    com:
      mayphyr:
        iotfeign: debug #com.cloud????


feign:
  client:
    config:
      default:
        loggerLevel: basic
  httpclient:
    max-connections-per-route: 50 #??????????
    enabled: false  #??httpClient???
    max-connections: 200  #?????

