spring:
  main:
    allow-circular-references: true  #允许循环引用
  application:
    name: lora-backend
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      server-addr: 124.221.8.81:8848   #nacos服务端地址
      discovery:
        cluster-name: SH # 集群名称，这里的明治可以随便取
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-ioc2c5yu.sql.tencentcdb.com:27195/lora
    username: xiancai
    password: zGpBWzbbb8A4Ekdb
  redis:
    host: r-m5e0adwqarpi0gv2h2pd.redis.rds.aliyuncs.com
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: Wjk5377197
mybatis-plus:
  configuration:
   # map-underscore-to-camel-case: true 默认也是开启的，会自动将下划线转为驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8090
  servlet:
    context-path: /api/lora

mqtt:
  broker-url: tcp://124.223.84.253:1883
  client-id: PURE_SUN
  username: PURE_SUN
  password: 123456
  web-topic: sms_pub
  hard-topic: sms_sub