 spring:
  application:
    name: iot-gateway
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sh-cynosdbmysql-grp-ioc2c5yu.sql.tencentcdb.com:27195/lora
    username: xiancai
    password: zGpBWzbbb8A4Ekdb
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    host: r-m5e0adwqarpi0gv2h2pd.redis.rds.aliyuncs.com
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: Wjk5377197
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    nacos:
      server-addr: 124.221.8.81:8848   #nacos服务端地址
      discovery:
        cluster-name: SH # 集群名称，这里的明治可以随便取
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "GET, PUT, POST, DELETE"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-center # 路由表示，必须唯一
          uri: lb://iot-usercenter    #  这个lb代表负载均衡的意思   路由的目标哦地址
          predicates:
            - Path=/api/iotuser/**   #路径断言，判断路径是否以/api/user开头，如果是则符合
            - Before=2099-01-20T17:42:47.789-07:00[America/Denver]   #路由断言工厂，有十几种断言工厂，什么时候用到了去官方文档查就可以了
            - Before=2099-01-20T17:42:47.789-07:00[America/Denver]
        - id: decider # 路由表示，必须唯一
          uri: lb://iot-decider    #  这个lb代表负载均衡的意思   路由的目标哦地址
          predicates:
            - Path=/api/decider/**   #路径断言，判断路径是否以/api/user开头，如果是则符合
            - Before=2099-01-20T17:42:47.789-07:00[America/Denver]   #路由断言工厂，有十几种断言工厂，什么时候用到了去官方文档查就可以了
            - Before=2099-01-20T17:42:47.789-07:00[America/Denver]
        - id: lora # 路由表示，必须唯一
          uri: lb://lora-backend    #  这个lb代表负载均衡的意思   路由的目标哦地址
          predicates:
            - Path=/api/lora/**   #路径断言，判断路径是否以/api/user开头，如果是则符合
            - Before=2099-01-20T17:42:47.789-07:00[America/Denver]   #路由断言工厂，有十几种断言工厂，什么时候用到了去官方文档查就可以了
            - Before=2099-01-20T17:42:47.789-07:00[America/Denver]
      default-filters:
        - AddRequestHeader=mayphyr, gateway
 mybatis-plus:
   configuration:
     map-underscore-to-camel-case: false
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   global-config:
     db-config:
       logic-delete-field: isDelete # 全局逻辑删除的实体字段名
       logic-delete-value: 1 # 逻辑已删除值（默认为 1）
       logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
 server:
   address: 0.0.0.0
   port: 8103
   servlet:
     context-path: /api
     # cookie 30 天过期
     session:
       cookie:
         max-age: 2592000
 # 开启网关的日志
 logging:
   level:
     org:
       springframework:
         cloud:
           gateway: trace

 feign:
   client:
     config:
       default:
         logger-level: FULL